### ISSUE TITLE
Write the Queue implementation in any language

### ISSUE THREAD

**Issue by ashwanitr001** [OpenAlgos/Data_structures-and-Algorithms#2]
**Is your feature request related to a problem? Please describe.**
* This repo has the implemented of queue in Python, to support other people Please write your implementation in language of your choice

**Comment by Stark-Tony** [comment]
@can i take the issue?

**Comment by Stark-Tony** [comment]
@ashwanitr001  can I take the issue?

**Comment by ashwanitr001** [comment]
Yeah,sure go with it
