### ISSUE TITLE
Implement Linear Search in language of your choice

### ISSUE THREAD

**Issue by ashwanitr** [OpenAlgos/Data_structures-and-Algorithms#38]
* Implement Linear Search in language of your choice. Please maintain the coding standards and go through the Readme file.

**Comment by shivam8287** [comment]
i am taking this issue for cpp.

**Comment by Akshay-911** [comment]
I can take this for cpp.

**Comment by RyanMan56** [comment]
I'll take this for Javascript

**Comment by ashwanitr001** [comment]
@shivam8287  @Akshay-911  Please go ahead and Please follow the coding and naming standards, plus try to add useful comments in the code.

**Comment by aansari4599** [comment]
I'll take this for C.

**Comment by ashwanitr001** [comment]
@aansari4599 @RyanMan56 You are welcome to contribute to this repository.

**Comment by shivam8287** [comment]
@ashwanitr001  added the file ilinear_search.py in PR #46 . please check that

**Comment by ashwanitr001** [comment]
I'll check everyone's implementations, in the mean time you can join our group at https://gitter.im/OpenAlgos/community

**Comment by RyanMan56** [comment]
@ashwanitr001 this was a nice introduction to open source. Please review PR #50

**Comment by ivaibhavjindal** [comment]
I'll take this up for java

**Comment by aansari4599** [comment]
hey , I have added linear search implementation in C. please review.

**Comment by amul123** [comment]
@ashwanitr001 i will do this in c

**Comment by Ad-S** [comment]
is this project still active 
i want to do it by c

**Comment by pratyanshupandey** [comment]
I think people have already submitted codes for linear search. Can I do binary search in C?

**Comment by ashwanitr001** [comment]
@pratyanshupandey  yes you can, but first create an issue and then assign it to yourself

**Comment by omkarsgit** [comment]
I have created the program in Go lang. Creating PR now.

**Comment by ashwanitr** [comment]
Closed
