### ISSUE TITLE
Graph Algorithm in Python in Wrong directory

### ISSUE THREAD

**Issue by iamprayush** [OpenAlgos/Data_structures-and-Algorithms#39]
I added graph algorithms and Union Find in PR #16. I added it in the proper folder but somehow currently it's present in Data_structures-and-Algorithms/Algorithms/Javascript/ instead of under Python.    

Also, the Union Find Algorithm I added is nowhere to be found. @ashwanitr001 pls look into this.

**Comment by ashwanitr001** [comment]
Hi @iamprayush  I have made the required changes. Please create the union_find file again and Create a separate PR.
